# Problem 7 - 2D Convolution

## Interview question

Implement 2D convolution for a single-channel image using NumPy. Support padding and stride.

## What is being asked

You need to correctly handle indexing, output shape, padding, and stride. This is a classic deep learning operations question.

## Clarifying questions

- Is this convolution or cross-correlation? Deep learning libraries usually implement cross-correlation.
- Single channel or multi-channel?
- Should I support batches?
- Should padding be zero padding?

## Solution

In [86]:
import numpy as np

"""
Input X (HxW), K (kcxkw), stride (s), padding (0 or 1)
Output O (H'xW')

Example --> X = (32, 32) and K = (3, 3) and stride = 1 and padding = 0
            Output (30, 30)

Example --> X = (32, 32) and K = (3, 3) and stride = 1 and padding = 1
            X' = (34, 34)
            Output (32, 32)

Example --> X = (32, 32) and K = (3, 3) and stride = 2 and padding = 0
            Output (15, 15)

x x x x x
x x x x x
x x x x x
x x x x x
x x x x x

"""

def conv2d(X, K, stride = 1, padding = 1):
    if padding:
        X = np.pad(X, ((padding, padding), (padding, padding)), mode="constant")

    H, W = X.shape
    kh, kw = K.shape
    Oh = (H-kh) // stride + 1
    Ow = (W-kw) // stride + 1

    O = np.zeros((Oh, Ow))

    for i in range(0, O.shape[0]):
        for j in range(0, O.shape[1]):
            x_i = i*stride
            x_j = j*stride

            O[i, j] = np.sum(X[x_i: x_i+kh, x_j: x_j+kw] * K)

    return O

In [89]:
import torch as th

H = 35
kh = 3
stride = 1
padding = 1 

X = np.random.rand(1, 1, H, H)
K = np.random.rand(1, 1, kh, kh)
out_torch = th.nn.functional.conv2d(th.tensor(X),th.tensor(K), padding=padding, stride=stride)[0, 0].numpy()
out_np = conv2d(X[0, 0], K[0, 0], stride)

print(np.allclose(out_torch, out_np,1e-10, 1e-8))
print(out_torch)
print(out_np)
print(out_torch-out_np)


True
[[0.74859241 0.87891323 0.94654818 ... 1.61882762 1.73303751 1.25732097]
 [1.35979449 1.84404654 2.24938982 ... 2.74370109 2.43596355 1.6111062 ]
 [1.90969626 2.34506196 1.95684132 ... 2.38823798 2.14313847 1.53035033]
 ...
 [2.29569834 2.44501665 2.22697084 ... 2.65733127 2.58762299 1.48105442]
 [1.79252485 2.51098283 2.68992488 ... 2.25953083 2.13233195 1.72400693]
 [1.14843083 1.22875025 1.75946746 ... 1.64495925 1.68859399 1.17373423]]
[[0.74859241 0.87891323 0.94654818 ... 1.61882762 1.73303751 1.25732097]
 [1.35979449 1.84404654 2.24938982 ... 2.74370109 2.43596355 1.6111062 ]
 [1.90969626 2.34506196 1.95684132 ... 2.38823798 2.14313847 1.53035033]
 ...
 [2.29569834 2.44501665 2.22697084 ... 2.65733127 2.58762299 1.48105442]
 [1.79252485 2.51098283 2.68992488 ... 2.25953083 2.13233195 1.72400693]
 [1.14843083 1.22875025 1.75946746 ... 1.64495925 1.68859399 1.17373423]]
[[ 0.00000000e+00 -1.11022302e-16  0.00000000e+00 ...  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [